# numkit .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

sphinx:
    configuration: docs/source/conf.py
    
# Optionally build your docs in additional formats such as PDF and ePub
formats: all


# install package
python:
   install:
      - method: pip
        path: .

conda:
    environment: ci/readthedocs/environment.yml
