name: CI

on:
  # run once a day at 3:33 UTC
  schedule:
    - cron: "33 3 * * *"
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Test ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        exclude:
          - os: macOS-latest
            python-version: 3.6
          - os: macOS-latest
            python-version: 3.7
          - os: macOS-latest
            python-version: 3.9
          - os: windows-latest
            python-version: 3.6
          - os: windows-latest
            python-version: 3.7
          - os: windows-latest
            python-version: 3.9

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install pytest, pytest plugins
      run: |
        python -m pip install wheel
        python -m pip install pytest pytest-cov pytest-pep8

    - name: Install main dependencies
      run: |
        python -m pip install six
        python -m pip install --only-binary=numpy numpy
        python -m pip install --only-binary=scipy scipy 

    - name: Install package
      run: |
        python -m pip install .

    - name: Run tests
      run: |
        pytest -v --cov=numkit --cov-report=xml --color=yes src/numkit/tests

    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
        file: ./coverage.xml
        fail_ci_if_error: true
